//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ConfigPL {
    
    private ConfigPLPL[] configField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("PL", IsNullable=false)]
    public ConfigPLPL[] Config {
        get {
            return this.configField;
        }
        set {
            this.configField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ConfigPLPL {
    
    private string linieField;
    
    private ushort anzahlGeräteField;
    
    private bool aktivField;
    
    /// <remarks/>
    public string Linie {
        get {
            return this.linieField;
        }
        set {
            this.linieField = value;
        }
    }
    
    /// <remarks/>
    public ushort AnzahlGeräte {
        get {
            return this.anzahlGeräteField;
        }
        set {
            this.anzahlGeräteField = value;
        }
    }
    
    /// <remarks/>
    public bool Aktiv {
        get {
            return this.aktivField;
        }
        set {
            this.aktivField = value;
        }
    }
}
