
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 

namespace ComosToEplan
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class MSRKaesten
    {

        private MSRKaestenRIO[] remoteIOField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RIO", IsNullable = false)]
        public MSRKaestenRIO[] RemoteIO
        {
            get
            {
                return this.remoteIOField;
            }
            set
            {
                this.remoteIOField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MSRKaestenRIO
    {

        private string typField;

        private string bMKField;

        private string networktypField;

        private string masterField;

        private byte adresseField;

        private byte subnetField;

        private bool ventilinselField;

        private byte ersterSteckplatzVentileInselField;

        /// <remarks/>
        public string Typ
        {
            get
            {
                return this.typField;
            }
            set
            {
                this.typField = value;
            }
        }

        /// <remarks/>
        public string BMK
        {
            get
            {
                return this.bMKField;
            }
            set
            {
                this.bMKField = value;
            }
        }

        /// <remarks/>
        public string Networktyp
        {
            get
            {
                return this.networktypField;
            }
            set
            {
                this.networktypField = value;
            }
        }

        /// <remarks/>
        public string Master
        {
            get
            {
                return this.masterField;
            }
            set
            {
                this.masterField = value;
            }
        }

        /// <remarks/>
        public byte Adresse
        {
            get
            {
                return this.adresseField;
            }
            set
            {
                this.adresseField = value;
            }
        }

        /// <remarks/>
        public byte Subnet
        {
            get
            {
                return this.subnetField;
            }
            set
            {
                this.subnetField = value;
            }
        }

        /// <remarks/>
        public bool Ventilinsel
        {
            get
            {
                return this.ventilinselField;
            }
            set
            {
                this.ventilinselField = value;
            }
        }

        /// <remarks/>
        public byte ersterSteckplatzVentileInsel
        {
            get
            {
                return this.ersterSteckplatzVentileInselField;
            }
            set
            {
                this.ersterSteckplatzVentileInselField = value;
            }
        }
    }
}
