//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 

namespace ComosToEplan
{
    /// <remarks/>
    //   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    //   [System.SerializableAttribute()]
    // [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    // [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    // [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]

    public partial class MSRGeraete
    {

        private MSRGeraeteMembranpumpe[] pumpenField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Membranpumpe", IsNullable = false)]
        public MSRGeraeteMembranpumpe[] Pumpen
        {
            get
            {
                return this.pumpenField;
            }
            set
            {
                this.pumpenField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MSRGeraeteMembranpumpe
    {

        private string bMKField;

        private string bezeichnungField;

        private byte plField;

        private byte ebeneField;

        private MSRGeraeteMembranpumpeSensoren sensorenField;

        private MSRGeraeteMembranpumpeMembranpumpe membranpumpeField;

        /// <remarks/>
        public string BMK
        {
            get
            {
                return this.bMKField;
            }
            set
            {
                this.bMKField = value;
            }
        }

        /// <remarks/>
        public string Bezeichnung
        {
            get
            {
                return this.bezeichnungField;
            }
            set
            {
                this.bezeichnungField = value;
            }
        }

        /// <remarks/>
        public byte PL
        {
            get
            {
                return this.plField;
            }
            set
            {
                this.plField = value;
            }
        }

        /// <remarks/>
        public byte Ebene
        {
            get
            {
                return this.ebeneField;
            }
            set
            {
                this.ebeneField = value;
            }
        }

        /// <remarks/>
        public MSRGeraeteMembranpumpeSensoren Sensoren
        {
            get
            {
                return this.sensorenField;
            }
            set
            {
                this.sensorenField = value;
            }
        }

        /// <remarks/>
        public MSRGeraeteMembranpumpeMembranpumpe Membranpumpe
        {
            get
            {
                return this.membranpumpeField;
            }
            set
            {
                this.membranpumpeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MSRGeraeteMembranpumpeSensoren
    {

        private string hubregelungField;

        private string membranüberwachung_außen_2Field;

        private string membranüberwachung_außen_1Field;

        private string membranüberwachung_innen_2Field;

        private string membranüberwachung_innen_1Field;

        /// <remarks/>
        public string Hubregelung
        {
            get
            {
                return this.hubregelungField;
            }
            set
            {
                this.hubregelungField = value;
            }
        }

        /// <remarks/>
        public string Membranüberwachung_außen_2
        {
            get
            {
                return this.membranüberwachung_außen_2Field;
            }
            set
            {
                this.membranüberwachung_außen_2Field = value;
            }
        }

        /// <remarks/>
        public string Membranüberwachung_außen_1
        {
            get
            {
                return this.membranüberwachung_außen_1Field;
            }
            set
            {
                this.membranüberwachung_außen_1Field = value;
            }
        }

        /// <remarks/>
        public string Membranüberwachung_innen_2
        {
            get
            {
                return this.membranüberwachung_innen_2Field;
            }
            set
            {
                this.membranüberwachung_innen_2Field = value;
            }
        }

        /// <remarks/>
        public string Membranüberwachung_innen_1
        {
            get
            {
                return this.membranüberwachung_innen_1Field;
            }
            set
            {
                this.membranüberwachung_innen_1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MSRGeraeteMembranpumpeMembranpumpe
    {

        private string bMKField;

        private string bezeichnungField;

        private byte plField;

        private byte ebeneField;

        private MSRGeraeteMembranpumpeMembranpumpeSensoren sensorenField;

        /// <remarks/>
        public string BMK
        {
            get
            {
                return this.bMKField;
            }
            set
            {
                this.bMKField = value;
            }
        }

        /// <remarks/>
        public string Bezeichnung
        {
            get
            {
                return this.bezeichnungField;
            }
            set
            {
                this.bezeichnungField = value;
            }
        }

        /// <remarks/>
        public byte PL
        {
            get
            {
                return this.plField;
            }
            set
            {
                this.plField = value;
            }
        }

        /// <remarks/>
        public byte Ebene
        {
            get
            {
                return this.ebeneField;
            }
            set
            {
                this.ebeneField = value;
            }
        }

        /// <remarks/>
        public MSRGeraeteMembranpumpeMembranpumpeSensoren Sensoren
        {
            get
            {
                return this.sensorenField;
            }
            set
            {
                this.sensorenField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MSRGeraeteMembranpumpeMembranpumpeSensoren
    {

        private string hubregelungField;

        private string membranüberwachung_außen_2Field;

        private string membranüberwachung_außen_1Field;

        private string membranüberwachung_innen_2Field;

        private string membranüberwachung_innen_1Field;

        /// <remarks/>
        public string Hubregelung
        {
            get
            {
                return this.hubregelungField;
            }
            set
            {
                this.hubregelungField = value;
            }
        }

        /// <remarks/>
        public string Membranüberwachung_außen_2
        {
            get
            {
                return this.membranüberwachung_außen_2Field;
            }
            set
            {
                this.membranüberwachung_außen_2Field = value;
            }
        }

        /// <remarks/>
        public string Membranüberwachung_außen_1
        {
            get
            {
                return this.membranüberwachung_außen_1Field;
            }
            set
            {
                this.membranüberwachung_außen_1Field = value;
            }
        }

        /// <remarks/>
        public string Membranüberwachung_innen_2
        {
            get
            {
                return this.membranüberwachung_innen_2Field;
            }
            set
            {
                this.membranüberwachung_innen_2Field = value;
            }
        }

        /// <remarks/>
        public string Membranüberwachung_innen_1
        {
            get
            {
                return this.membranüberwachung_innen_1Field;
            }
            set
            {
                this.membranüberwachung_innen_1Field = value;
            }
        }
    }
}