//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 

namespace ComosToEplan
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class MSRGeraete
    {

        private MSRGeraeteGerät[] feldgerraeteField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Gerät", IsNullable = false)]
        public MSRGeraeteGerät[] Feldgerraete
        {
            get
            {
                return this.feldgerraeteField;
            }
            set
            {
                this.feldgerraeteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MSRGeraeteGerät
    {

        private string herstellerField;

        private string gerätetypField;

        private string bestellcodeField;

        private string beschreibungField;

        private string anschluß_PlusField;

        private string anschluß_MinusField;

        /// <remarks/>
        public string Hersteller
        {
            get
            {
                return this.herstellerField;
            }
            set
            {
                this.herstellerField = value;
            }
        }

        /// <remarks/>
        public string Gerätetyp
        {
            get
            {
                return this.gerätetypField;
            }
            set
            {
                this.gerätetypField = value;
            }
        }

        /// <remarks/>
        public string Bestellcode
        {
            get
            {
                return this.bestellcodeField;
            }
            set
            {
                this.bestellcodeField = value;
            }
        }

        /// <remarks/>
        public string Beschreibung
        {
            get
            {
                return this.beschreibungField;
            }
            set
            {
                this.beschreibungField = value;
            }
        }

        /// <remarks/>
        public string Anschluß_Plus
        {
            get
            {
                return this.anschluß_PlusField;
            }
            set
            {
                this.anschluß_PlusField = value;
            }
        }

        /// <remarks/>
        public string Anschluß_Minus
        {
            get
            {
                return this.anschluß_MinusField;
            }
            set
            {
                this.anschluß_MinusField = value;
            }
        }
    }
}